gpxviewr/gpxviewr/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from django.contrib.auth import views as auth_views

from baseweb.views import (
    StatusView,
    RobotsTxtView,
    GPXFileListView,
    GPXFileDetailView,
    GPXFileEditView,
    GPXTrackDownloadView,
    GPXFileUserSegmentSplitDownloadView,
    GPXFileUserSegmentSplitView,
    GPXWayPointPathFromTrackDownloadView,
    WaypointDetailView,
    IndexView,
)

from baseweb.viewset import (
    GPXFileViewSet,
    GPXWayPointTypeViewSet,
)

from gcollection.views import (
    GCollectionDetailView,
    GCollectionDetailOGImageView,
    GCollectionDetailTokenAuthFailedView,
    GCollectionListView,
    GCollectionCreateView,
    GCollectionShareDeleteView,
    GCollectionShareCreateView,
    GCollectionGPXFileDownloadView,
    GCollectionLogoutView,
    GCollectionLoginView,
    GCollectionProfileView,
)

from gcollection.viewset import (
    GCollectionViewSet,
    GCollectionGPXFileViewSet,
    GCollectionWaypointViewSet,
)

router = DefaultRouter()
router.register(r'gpxfile', GPXFileViewSet, basename='gpxfile')
router.register(r'gpxwaypointtype', GPXWayPointTypeViewSet)
router.register(r'gc', GCollectionViewSet)
router.register(r'gc-gpxfile', GCollectionGPXFileViewSet)
router.register(r'gc-waypoint', GCollectionWaypointViewSet)

urlpatterns = [
    path('social/', include('social_django.urls', namespace="social")),
    path('api/', include(router.urls)),
    path('robots.txt', RobotsTxtView.as_view(), name='robots'),
    path('status', StatusView.as_view(), name='status'),
    path('', IndexView.as_view(), name='root'),
    path('gpxtrack/<slug:slug>', GPXFileDetailView.as_view(), name='gpx-file-detail'),
    path('gpxtrack/<slug:slug>/edit', GPXFileEditView.as_view(), name='gpx-file-edit'),
    path('gpxtrack/<slug:slug>/track_splits', GPXFileUserSegmentSplitView.as_view()),
    path('gpxtrack/<slug:slug>/waypoint/<int:pk>', WaypointDetailView.as_view()),
    path('gpxtrack/<slug:slug>/download', GPXTrackDownloadView.as_view(), name='gpx-track-download-detail'),
    path('gpxtrack/<slug:slug>/download_gpx_track_to_waypoint/<int:pk>', GPXWayPointPathFromTrackDownloadView.as_view()),
    path('gpxtrack/<slug:slug>/user_segment_split_download/<int:pk>', GPXFileUserSegmentSplitDownloadView.as_view()),
    path('gpxtrack/', GPXFileListView.as_view(), name='gpx_file_list'),
    path('gc/token-auth-failed', GCollectionDetailTokenAuthFailedView.as_view(), name='gcollection_token_failed'),
    path('gc/', GCollectionListView.as_view(), name='gcollection_list'),
    path('gc/<int:pk>', GCollectionDetailView.as_view(), name='gcollection_detail'),
    path('gc/<int:pk>/og_image.jpg', GCollectionDetailOGImageView.as_view(), name='gcollection_detail_og_image'),
    path('gc/add', GCollectionCreateView.as_view(), name='gcollection_create'),
    path('gc_share/<int:pk>/delete', GCollectionShareDeleteView.as_view(), name='gc_share_delete'),
    path('gc_share/add', GCollectionShareCreateView.as_view(), name='gc_share_create'),
    path('accounts/login/', GCollectionLoginView.as_view(), name='login'),
    path('accounts/logout/', GCollectionLogoutView.as_view(), name='logout'),
    path('accounts/profile/', GCollectionProfileView.as_view(), name='profile'),
    path('gc_gpx_file/<int:pk>/download', GCollectionGPXFileDownloadView.as_view(), name="gc_gpx_file_download"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpxviewr/baseweb/models.py
from pathlib import Path
import secrets
import time
import os
import geojson
import json
import phonenumbers
from geopy import distance as geopy_distance
from datetime import timedelta

from django.utils import timezone
from django.core.files.storage import FileSystemStorage
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.gis.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.gis.measure import Distance
from django.contrib.gis.db.models.functions import Distance as FDistance
from django.contrib.gis.geos import Point
from django.urls import reverse
from django.db.models.signals import post_delete, pre_delete
from django.db.models import Sum
from django.dispatch import receiver

from django_extensions.db.models import TimeStampedModel

import overpy

import numpy
import pandas
from gpx import GPX, Waypoint, Track
from gpx.track_segment import TrackSegment
from gpx.waypoint import Link


fs = FileSystemStorage(location=settings.LOCAL_STORAGE_DIRECTORY)


def generate_slug_token():
    return secrets.token_urlsafe(30)


def generate_default_delete_after_date():
    return (timezone.now() + timedelta(days=10)).strftime('%Y-%m-%d')


class GPXFile(TimeStampedModel):
    job_status_fields = {
        1: 'uploaded',
        2: 'gpx_track_loading',
        3: 'osm_query',
        4: 'finished',
        5: 'error',
    }
    line_colors = [
        '#2f2faf',
        '#ff0066',
        '#1f1fbf',
        '#3ef0fb',
        '#502968',
        '#448137',
    ]

    slug = models.SlugField(default=generate_slug_token, editable=False, max_length=50)
    name = models.CharField(max_length=100, null=False, blank=False)
    wpt_options = models.JSONField(default=dict)
    job_status = models.IntegerField(default=1, null=False)
    delete_after = models.DateField(null=False, blank=False)

    file = models.FileField(storage=fs, upload_to="gpx_track/%Y/%m/%d/")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', '-created',]

    def get_absolute_url(self) -> str:
        return reverse("gpx-file-detail", kwargs={"slug": self.slug})

    def save(self, **kwargs):
        if self.name is None or self.name == '':
            self.name = self.file.name.replace('.gpx', '')

        return super().save(**kwargs)

    def is_demo_track(self) -> bool:
        return self.slug == settings.DEMO_TRACK_SLUG

    def get_job_status(self) -> str:
        return self.job_status_fields.get(self.job_status, 'unkown')

    def job_is_finished(self) -> bool:
        if self.get_job_status() == 'finished':
            return True
        return False

    def get_all_segments_primary_keys(self):
        return GPXTrackSegment.objects.all().filter(track__in=self.tracks.all().values_list('pk'))

    def get_waypoint_types(self) -> list:
        data = []
        for wtp in GPXWayPointType.objects.all():
            o = self.wpt_options.get(wtp.name, {})

            if o.get('enabled', False) is True:
                data.append(wtp)

        return data

    def get_waypoint_types_with_entries(self):
        wtps = []
        for wtp in GPXWayPointType.objects.all():
            wtps.append({
                'object': wtp,
                'waypoints': self.waypoints.all().filter(waypoint_type=wtp),
            })
        return wtps

    def generate_download_gpx_file(self, options) -> str:
        gpx = GPX()
        gpx.creator = 'GPX Tools by hggh'
        waypoints = []

        for w in self.waypoints.all().filter(waypoint_type__in=options).filter(hidden=False):
            wp = Waypoint()
            wp.lat = w.location.x
            wp.lon = w.location.y
            wp.name = w.name
            wp.sym = w.waypoint_type.gpx_sym_name

            if w.get_url():
                wp_link = Link()
                wp_link.href = w.get_url()
                wp_link.text = w.get_url()
                wp.links = [wp_link]

            waypoints.append(wp)

        gpx.waypoints = waypoints

        return gpx.to_string()

    def get_user_segment_splits(self, segment_pk=None) -> list:
        data = []

        if segment_pk is not None:
            segments = self.user_segments.all().filter(point_start__segment__id=segment_pk)
        else:
            segments = self.user_segments.all()

        data = []

        for s in segments:
            segment = {
                "name": s.name,
                "id": s.pk,
                "segment_pk": s.point_start.segment.id,
                "start": {
                    "number": s.point_start.number,
                    "lat": float(s.point_start.location.x),
                    "lon": float(s.point_start.location.y),
                },
                "end": {
                    "number": s.point_end.number,
                    "lat": float(s.point_end.location.x),
                    "lon": float(s.point_end.location.y),
                }
            }
            data.append(segment)

        return data

    def generate_waypoints(self, point_type, around_meters=None, around_duplicate=0) -> None:
        if around_meters is None:
            around_meters = point_type.around

        gpxfile = GPX.from_file(self.file.path)

        for track in gpxfile.tracks:
            for segment in track.trksegs:
                points = []
                curr = 0

                for point in segment.trkpts:
                    points.append((point.lat, point.lon))
                    curr += 1

                    if curr == 2000:
                        self.query_data_osm(
                            points=points,
                            around_meters=around_meters,
                            point_type=point_type,
                            around_duplicate=around_duplicate,
                        )
                        time.sleep(1)
                        points = []
                        curr = 0

                if len(points) > 0:
                    self.query_data_osm(
                        points=points,
                        around_meters=around_meters,
                        point_type=point_type,
                        around_duplicate=around_duplicate,
                    )
                    time.sleep(1)

    def query_data_osm(self, points, around_meters, point_type, around_duplicate) -> None:
        from .tasks import gpx_waypoint_find_route_from_track

        track_points = pandas.DataFrame(points, columns=["lat", "lon"])
        track_latlong_flatten = ",".join(track_points.to_numpy().flatten().astype("str"))

        api = overpy.Overpass()
        overpass_query = f"""
            [out:json][timeout: 500];
            (
                nwr["{point_type.osm_name}" {point_type.osm_query_type} "{point_type.osm_value}"](around:{around_meters},{track_latlong_flatten});
            );
            out center qt;
        """
        try:
            result = api.query(overpass_query)
        except overpy.exception.OverpassGatewayTimeout:
            print("OverpassGatewayTimeout - retry")
            time.sleep(4)
            self.query_data_osm(points=points, around_meters=around_meters, point_type=point_type, around_duplicate=around_duplicate)

        for node in result.get_nodes():
            wp = GPXTrackWayPoint(
                location=Point([node.lat, node.lon], srid=4326),
                waypoint_type=point_type,
                gpx_file=self,
                tags=node.tags,
            )
            if "name" in node.tags:
                wp.name = node.tags.get("name")

            c = GPXTrackWayPoint.objects.all().filter(
                location__distance_lt=(Point([node.lat, node.lon], srid=4326), Distance(m=around_duplicate)),
                waypoint_type=point_type,
                gpx_file=self,
            )
            if c.count() == 0:
                sp = GPXTrackSegmentPoint.objects.filter(segment__in=self.get_all_segments_primary_keys()).annotate(
                    distance=FDistance('location', Point([node.lat, node.lon], srid=4326))
                ).order_by('-distance').last()
                wp.track_segment_point_nearby = sp
                wp.save()
                if wp.is_camping_site() or wp.is_hotel():
                    gpx_waypoint_find_route_from_track.delay(wp.pk)

        for way in result.get_ways():
            wp = GPXTrackWayPoint(
                location=Point([way.center_lat, way.center_lon], srid=4326),
                waypoint_type=point_type,
                gpx_file=self,
                tags=way.tags,
            )
            if "name" in way.tags:
                wp.name = way.tags.get("name")

            c = GPXTrackWayPoint.objects.all().filter(
                location__distance_lt=(Point([way.center_lat, way.center_lon], srid=4326), Distance(m=around_duplicate)),
                waypoint_type=point_type,
                gpx_file=self,
            )
            if c.count() == 0:
                sp = GPXTrackSegmentPoint.objects.filter(segment__in=self.get_all_segments_primary_keys()).annotate(
                    distance=FDistance('location', Point([way.center_lat, way.center_lon], srid=4326))
                ).order_by('-distance').last()
                wp.track_segment_point_nearby = sp
                wp.save()
                if wp.is_camping_site() or wp.is_hotel():
                    gpx_waypoint_find_route_from_track.delay(wp.pk)

    def get_gpx_json_filename(self) -> str:
        return os.path.join(settings.LOCAL_GEOJSON_TEMP_DIRECTORY, f"gpx_file_info_{self.pk}.json")

    def get_json_data(self):
        if os.path.exists(self.get_gpx_json_filename()):
            return json.loads(Path(self.get_gpx_json_filename()).read_text())

        return None

    def load_file_to_database(self) -> None:
        json_data = []
        gpxfile = GPX.from_file(self.file.path)

gpxviewr/baseweb/models/gpx_track.py
from urllib.parse import urlparse

from django.contrib.gis.db import models
from django.db.models import Sum

from django_extensions.db.models import TimeStampedModel


class GPXTrack(TimeStampedModel):
    gpx_file = models.ForeignKey("GPXFile", on_delete=models.CASCADE, related_name='tracks')
    name = models.CharField(max_length=200, null=False, blank=False)
    distance = models.FloatField()
    link = models.URLField(max_length=6000, null=True)

    def __str__(self) -> str:
        return f"GPX Track {self.name}"

    class Meta:
        ordering = ['name',]

    def get_link_hostname(self):
        if self.link:
            url = urlparse(self.link)
            return url.hostname

        return None

    def get_human_distance(self) -> str:
        d = int(self.distance / 1000)
        return f"{d} km"

    def get_total_ascent(self) -> int:
        d = self.segments.all().aggregate(ascent=Sum('total_ascent'))

        if d.get('ascent', None):
            return int(d.get('ascent', None))

        return None

    def get_total_descent(self) -> int:
        d = self.segments.all().aggregate(descent=Sum('total_descent'))

        if d.get('descent', None):
            return int(d.get('descent', None))

        return None

gpxviewr/baseweb/models/gpx_track_segment.py
from django.contrib.gis.db import models

from django_extensions.db.models import TimeStampedModel


class GPXTrackSegment(TimeStampedModel):
    number = models.IntegerField(null=False, blank=False, default=0)
    track = models.ForeignKey("GPXTrack", on_delete=models.CASCADE, related_name='segments')
    distance = models.FloatField()
    total_ascent = models.FloatField(null=True, blank=False)
    total_descent = models.FloatField(null=True, blank=False)

    def __str__(self) -> str:
        return f"GPX Track {self.track.name} Segment {self.number}"

    class Meta:
        ordering = ['track__name', 'number',]

    def get_human_distance(self) -> str:
        d = int(self.distance / 1000)
        return f"{d} km"

gpxviewr/baseweb/forms.py
import os
from collections.abc import Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import GPXFile, GPXWayPointType, generate_default_delete_after_date
from .valhalla import ValhallaRouting
from gcollection.models import GUser


def waypoint_types_choices():
    c = []
    for p in GPXWayPointType.objects.all():
        c.append((p.pk, p.pk))

    return c


class GPXFileUpdateForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(attrs={'class': 'form-control'})
    )
    delete_after = forms.DateField(
        required=True,
        widget=forms.widgets.DateInput(
            attrs={'class': 'form-control', 'type': 'date'},
        )
    )
    perm_public_available = forms.BooleanField(
        initial=False,
        required=False,
        widget=forms.widgets.Select(
            attrs={'class': 'form-control'},
            choices=((True, 'Yes'), (False, 'No')),
        ),
    )
    class Meta:
        model = GPXFile
        fields = ['name', 'perm_public_available', 'delete_after',]


class GPXFileUploadForm(forms.ModelForm):
    wpt_options = forms.JSONField()
    file = forms.FileField()
    delete_after = forms.DateField(initial=generate_default_delete_after_date)
    bicycle_type = forms.ChoiceField(choices=ValhallaRouting.get_bicycle_types, widget=forms.Select(attrs={'class': 'form-select'}))
    user = forms.ModelChoiceField(
        queryset=GUser.objects.none(),
        required=False,
    )
    perm_public_available = forms.BooleanField(
        initial=True,
        required=False,
        widget=forms.widgets.CheckboxInput(),
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['user'].queryset = GUser.objects.all().filter(id=user.id)
        else:
            self.fields['user'].queryset = GUser.objects.none()

    class Meta:
        model = GPXFile
        fields = ["file", "wpt_options", "delete_after", "perm_public_available", "user"]

gpxviewr/baseweb/templates/_track_split.html
{% load static %}
{% if object.is_single_segement_and_single_track is False %}
<div class="alert alert-danger" role="alert">
    Track Splitting works better if GPX File contains only one Track with one Segment!
</div>
{% endif %}

<div class="modal" id="gpx-track-user-segment-split-choose-waypoints" tabindex="-1" data-bs-backdrop="false">
    <form id="gpx-track-user-segment-split-choose-waypoints-form" action="" method="get">
    <input type="hidden" name="include_waypoints" value="1"/>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Download GPX Track with POIs as Waypoints</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="gpx-track-user-segment-split-choose-waypoints-body">
        <div>Select which waypoints will includes into the Track:</div>
        {% for waypoint_type in object.get_waypoint_types %}
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" role="switch" name="{{waypoint_type.name}}" id="{{waypoint_type.name}}" checked>
            <label class="form-check-label" for="{{waypoint_type.name}}">{{waypoint_type.name }}</label>
        </div>
        <div class="ms-3 form-check form-switch">
            <input class="form-check-input" type="checkbox" role="switch" name="{{waypoint_type.name}}_bookmark" id="{{waypoint_type.name}}">
            <label class="form-check-label" for="{{waypoint_type.name}}_bookmark">only bookmarked</label>
        </div>
        {% endfor %}
        <hr/>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" role="switch" name="wp_mode_garmin" id="wp_mode_garmin" checked>
          <label class="form-check-label" for="wp_mode_garmin">Garmin Waypoint mode.<br/>
            The POI waypoint will be placed on the Track, not on the orginal position. Garmin supports only Waypoints directly on the track and Garmin will strip the name (after 15 chars) and supports only 200 waypoints per Track. (depends on your device)
          </label>
        </div>
        <hr/>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" role="switch" name="wp_mode_orginal" id="wp_mode_orginal" checked>
          <label class="form-check-label" for="wp_mode_orginal">Include POI on orginal position.</label>
        </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id="gpx-track-user-segment-split-choose-waypoints-download">Download!</button>
        </div>
      </div>
    </div>
    </form>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col">KM</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for split in object.user_segments.all %}
        <tr class="user-track-splits" data-id="{{split.pk}}" data-segment-id="{{ split.get_segment_id }}">
            <th scope="row">{{split.name}}</th>
            <td></td>
            <td>{{split.get_human_distance }}</td>
            <td>
                {% if split.get_total_ascent %}
                    <img src="{% static 'bootstrap-icons-1.11.2/arrow-up-right.svg' %}" title="Up"/>
                    {{ split.get_total_ascent }} m
                {% endif %}
                {% if split.get_total_descent %}
                <img src="{% static 'bootstrap-icons-1.11.2/arrow-down-right.svg' %}" title="Up"/>
                    {{ split.get_total_descent }} m
                {% endif %}
            </td>
            <td>
                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'bootstrap-icons-1.11.2/cloud-download.svg' %}" title="Download GPX Track"/>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/gpxtrack/{{object.slug}}/user_segment_split_download/{{split.pk}}" class="dropdown-item">Download GPX Track</a></li>
                        <li><a href="#" data-url="/gpxtrack/{{object.slug}}/user_segment_split_download/{{split.pk}}" class="dropdown-item gpx-user-segment-split-download-with-waypoints">Download GPX Track with POIs</a></li>
                    </ul>
                </div>
              </td>
        </tr>
        {%endfor %}
    </tbody>
</table>

gpxviewr/baseweb/templates/gpx_track_edit.html
{% extends "base.html" %}
{% load static %}

{% block html_title %}
<span class="d-md-none">{{ object.name|truncatechars:20 }}</span>
<span clasS="d-none d-md-inline">{{ object.name }}</span>
{% endblock %}

{% block split_track_button %}
{% endblock%}

{% block content %}
{% load static %}
<main class="col">
    <div class="container-sm pt-2">
        <form method="post" action="{% url 'gpx-file-edit' object.slug %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary mt-3" title="Update" value="Update"/>
        </form>
        <a href="{% url 'gpx-file-detail' object.slug %}">
            <button type="button" class="btn btn-info mt-3">Cancel</button>
        </a>
    </div>
</main>
{% endblock %}

gpxviewr/baseweb/templates/index.html
{% extends "base.html" %}
{% block opengraph %}
<meta property="og:title" content="GPXViewr"/>
<meta name="description" property="og:description" content="GPX Track Viewer with POI search based on OpenStreetMap"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="https://gpxviewr.genannt.name/static/preview.png"/>
{% endblock %}

{% block html_title %}GPX / OSM Tool{% endblock %}

{% block content %}

<div class="container">
<main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">

{% if demo_track %}
<div class="alert alert-light" role="alert">
    Demo Track: <a href="/gpxtrack/{{ demo_track.slug }}">{{ demo_track.name }}</a>
</div>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{message}}
        </div>
    {% endfor %}
</div>
{% endif %}

<div class="container" style="padding-top:15px; padding-bottom:20px;">
    Find toilets, camping sites and more POIs (Point of Interest) from OpenStreetMap along your GPX bikepacking route.<br/>
    Split GPX Track in realtime with preview on Map and download splitted tracks to your GPS device.
    <div class="collapse">
        Finde Toiletten, Camping Plätze und mehr von OpenStreetMap entlang deiner GPX Route für die Radreise.
    </div>
</div>
<form method="post" id="gpx_track_upload" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row mb-3">
        <label for="inputFile" class="col-sm-2 col-form-label">GPX Track</label>
        <div class="col-sm-10">
            <input type="file" class="form-control" name="file" required id="id_file" accept=".gpx">
            <input type="hidden" class="form-control" name="name" id="id_name">
            the tool works very well with GPX Tracks downloaded from Komoot or <a href="https://brouter.m11n.de/" target="_blank">Brouter</a>
        </div>
    </div>
    <div class="row mb-3">
        <label for="bicycle_type_option" class="col-sm-2 col-form-label">bicycle type</label>
        <div class="col-sm-10">
            {{form.bicycle_type}}
            only needed if camping or hotel is used. works only in Europe. Route from the Track to the POI will be calculated with Valhalla Routing Engine.
        </div>
    </div>
    <div class="row mb-3">
        <label for="delete_after" class="col-sm-2 col-form-label">delete after</label>
        <div class="col-sm-5">
            <input type="date" class="form-control" min="{% now "Y-m-d" %}" name="delete_after" required id="id_delete_after" value="{{form.delete_after.value}}">
        </div>
    </div>
    <div class="row mb-3">
        <label for="perm_public_available" class="col-sm-2 col-form-label">public available via URL</label> 
        <div class="col-sm-10">
            <input type="hidden" name="user" value="{% if user.is_authenticated %}{{user.id}}{% endif %}"/>
            <select class="form-select" name="perm_public_available" id="id_perm_public_available" {% if user.is_authenticated %}{%else%}disabled{% endif %}>
                {% if user.is_authenticated %}
                <option value="true">Yes</option>
                <option value="false" selected>No</option>
                {% else %}
                <option value="true" selected>Yes</option>
                <option value="false">No</option>
                {% endif %}
            </select>
            If you have no account the GPX Track with the Waypoints (POI) are available via the URL. Every person who knows the secret URL can access the Track and modify the Segment Splits.<br/>
            If you log in, you can select <i>no</i>, the GPX Track is only available for your User.
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            type
        </div>
        <div class="col">
            enabled
        </div>
        <div class="col">
            around (in meters)
        </div>
        <div class="col">
            no duplicate within ... meters
        </div>
    </div>
    {% for wpt in waypoint_types %}
    <div class="row g-3 waypoint_types" data-wpt-name="{{wpt.name}}" data-wpt-name-html="{{wpt.html_id}}">
        <div class="col">{{ wpt.name }}</div>
        <div class="col">
            <input class="form-check-input" type="checkbox" value="" id="{{wpt.html_id}}" {%if wpt.checked %}checked{% endif %}>
        </div>
        <div class="col">
            <input type="number" class="form-control" id="{{wpt.html_id}}_around" value="{{ wpt.around }}" min="0" max="{{ wpt.around_max }}" step="10" required>
        </div>
        <div class="col">
            <input type="number" class="form-control" id="{{wpt.html_id}}_around_duplicate" value="{{ wpt.around_duplicate }}" min="0" step="10" required>
        </div>
    </div>
    {% endfor %}
    <div class="row mb-3">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col" style="text-align: right;"><small><a href="#" id="waypoint_types_reset_to_default" title="Reset the around and enabled Waypoints to default values.">Reset Values to Default</a></small></div>
    </div>
    <input type="hidden" name="wpt_options" value="{dd:ddd}" id="wpt_options">
    <button type="submit" class="btn btn-primary">Upload GPX Track!</button>
</form>

</main>
</div>

{% if uploaded_tracks %}
<div class="container">
    <h5>your uploaded GPX tracks:</h5>
    <ul class="list-group list-group-flush">
        {% for gpx_track in uploaded_tracks %}
        <li class="list-group-item"><a href="{% url 'gpx-file-detail' gpx_track.slug %}">{{gpx_track.name }} ({{gpx_track.created }})</a></li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endblock %}